# Spring Boot 설정
spring:
  application:
    name: nbbang-auth, common, jwt-common, member-datasource     # common 공통 프로퍼티 불러오기
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8197
  rabbitmq:
    host: 129.154.222.27
    port: 5672
    username: nbbang
    password: nbbang-dev!@#
  main:
    allow-bean-definition-overriding: true
# 서버 설정
server:
  port: 9100
  servlet:
    context-path: /nbbang-auth
# acutator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh
# 환경 파일 복호화
encrypt:
  key-store:
    #    내 로컬로 하면 돌아가는데 그러면 서버 배포하면 어케하지..?
    location: file:///Users/zayson/Desktop/Zayson Project/엔빵/nbbang-config.jks
    alias: nbbang-config-key
    password: config-access
#    location: file:///home/ubuntu/nbbang/key/nbbang-config.jks