# Spring Boot 설정
spring:
  application:
    name: nbbang-auth, common, jwt-common, member-datasource     # common 공통 프로퍼티 불러오기
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8197
  rabbitmq:
    host: 129.154.222.27
    port: 5672
    username: nbbang
    password: nbbang-dev!@#
  main:
    allow-bean-definition-overriding: true
# 서버 설정
server:
  port: 9100
  servlet:
    context-path: /nbbang-auth
# acutator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh